In [21]:
import pandas as pd
from google.colab import drive
import os
drive.mount('/content/gdrive')

%cd '/content/gdrive/MyDrive/DATA_SCIENCE_LUCIA_TORRE/ARCHIVOS_CSV'
airbnb_df= pd.read_csv('Airbnb.csv',sep=',')
airbnb_df.head()

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
/content/gdrive/MyDrive/DATA_SCIENCE_LUCIA_TORRE/ARCHIVOS_CSV

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (25) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$ 193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$ 28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$ 124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$ 74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$ 41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [22]:
airbnb_df.shape

(102599, 26)

In [29]:
airbnb_df['verified'] = airbnb_df['host_identity_verified'].apply(lambda x:'yes'if x=='verified' else 'no')
airbnb_df.head()


#data = {'first_name': ['Jon', 'Bill', 'Maria', 'Emma']}
#df = pd.DataFrame(data)

#airbnb_df['name_match'] = airbnb_df['first_name'].apply(lambda x: 'Match' if x == 'Bill' else 'Mismatch')

#print(df)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,verified
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,no
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,yes
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN,no
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN,no
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,yes

In [43]:
X = airbnb_df[['id', 'host id']]

y = airbnb_df.verified

from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=1)

X_train

             id      host id
59146  33667672  30332702788
78667  44449120  42724398600
26675  15733939  68586170154
55778  31807525  48771249829
47043  26983185   5961819884
...         ...          ...
50057  28647817  20965335576
98047  55152694  13723087476
5192    3868878  64236744953
77708  43919464   5412850469
98539  55424426  71288649670

[82079 rows x 2 columns]

In [44]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

logr=LogisticRegression()


logr.fit(X_train, y_train)

y_pred=logr.predict(X_test)

print('accuracy', accuracy_score(y_test, y_pred))
print('confusion_matrix', confusion_matrix(y_test, y_pred))
print('classification', classification_report(y_test, y_pred))

accuracy 0.4934697855750487
confusion_matrix [[    0 10394]
 [    0 10126]]

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

classification               precision    recall  f1-score   support

          no       0.00      0.00      0.00     10394
         yes       0.49      1.00      0.66     10126

    accuracy                           0.49     20520
   macro avg       0.25      0.50      0.33     20520
weighted avg       0.24      0.49      0.33     20520

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Conclusión:

Un valor de Accuracy de 0,49 indica que practicamente la mitad de las predicciones realizadas fueron acertadas. Se busca tener un valor cercano a 0,9 como mínimo. Un Accuracy de 0,49 indica que es un modelo demasiado sesgado, es decir que no va a ser muy exacto en sus predicciones y que por lo tanto no va a ser útil.